version: '3'

services:
  nginx:
    build: docker/nginx
    ports:
      - ${HTTPD_PORT}:80
    volumes:
      - ./docker/nginx/default:/etc/nginx/sites-available/default:ro
      - .:/var/www/:delegated
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
      - .:/var/www/:delegated
      - ./docker/php-fpm/fpm-pool.conf:/etc/php/7.1/fpm/pool.d/www.conf:ro
    working_dir: /var/www/
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_HOST=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    entrypoint: /bin/sh -c "/docker-entrypoint.sh mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
